// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

// Assembly Identity Attributes
// Three attributes, together with a strong name (if applicable), determine the
// identity of an assembly: name, version, and culture. These attributes form 
// the full name of the assembly and are required when referencing the assembly
// in code. You can use attributes to set an assembly's version and culture. 
// The compiler or the Assembly Linker (Al.exe) sets the name value when the 
// assembly is created, based on the file containing the assembly manifest.

    // Version information for an assembly consists of the following four values:
    //
    //      Major Version
    //      Minor Version 
    //      Build Number
    //      Revision
    //
    // You can specify all the values or you can default the Build and Revision Numbers by using 
    // the '*' as shown below:
    // [assembly: AssemblyVersion("1.0.*")]
    //
    // If "*" is used for Build number, the number of days since the year 2000. If "*" is used for 
    // Revision, the number of seconds since midnight (divided by 2) [IT IS NOT RANDOM].
    // 
    // Assembly values can be referenced in code:
    // string version = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString();

	// [assembly: AssemblyVersion("This is set by build process")]

[assembly: AssemblyVersion("1.4.14050.26983")]
[assembly: AssemblyFileVersion("1.4.14050.26983")]

[assembly: AssemblyProduct("Producer Contact")]
[assembly: AssemblyCompany("Dairylea Cooperative, Inc.")]
[assembly: AssemblyCopyright("Copyright © 2013-2014 Dairylea Cooperative, Inc. All Rights Reserved")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif


