/// <copyright file="GlobalAssemblyVersion.cs" company="Dairylea Cooperative, Inc.">
///     Copyright © 2013-2014 Dairylea Cooperative, Inc. All Rights Reserved.
/// </copyright>
/// <remarks>
///     This code was generated by a tool. Any changes made manually will be lost
///     the next time this code is regenerated.
/// </remarks>
///

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

//      Major Version
//      Minor Version 
//      Build Number
//      Revision
// 
// Major and minor version are hard-coded.
// Build number is: [two-digit year][three-digit day-of-year]
// Revision is: the number of seconds since midnight (divided by 2)
[assembly: AssemblyVersion("1.4.14058.22873")]
[assembly: AssemblyFileVersion("1.4.14058.22873")]

[assembly: AssemblyProduct("Producer Contact")]
[assembly: AssemblyCompany("Dairylea Cooperative, Inc.")]
[assembly: AssemblyCopyright("Copyright © 2013-2014 Dairylea Cooperative, Inc. All Rights Reserved.")]

// got debug
[assembly: AssemblyConfiguration("Debug")]
	
