/// <copyright file="GlobalAssemblyVersion.cs" company="Dairylea Cooperative, Inc.">
///     Copyright © 2013-2014 Dairylea Cooperative, Inc. All Rights Reserved.
/// </copyright>
/// <remarks>
///     This code was generated by a tool. Any changes made manually will be lost
///     the next time this code is regenerated.
/// </remarks>
///

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

//      Major Version
//      Minor Version 
//      Build Number
//      Revision
// 
// Major and minor version are hard-coded.
// Build number is: [two-digit year][three-digit day-of-year]
// Revision is: the number of seconds since midnight (divided by 5)
[assembly: AssemblyVersion("1.4.14170.12063")]
[assembly: AssemblyFileVersion("1.4.14170.12063")]

[assembly: AssemblyProduct("ProducerCRM")]
[assembly: AssemblyCompany("Dairylea Cooperative, Inc.")]
[assembly: AssemblyCopyright("Copyright © 2013-2014 Dairylea Cooperative, Inc. All Rights Reserved.")]

// did not find debug 
// did not find trace
// did not find beta 
// did not find Alpha 
// did not find AlphaConfig 
[assembly: AssemblyConfiguration("Release")]

